version: "1.0"
# M3.7: Agent keys ARE the roles - no separate role field
agents:
  Writer:
    image: "holt-writer-recipe-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: rw
    # M3.9: Simple health check example
    health_check:
      command: ["true"]

  Validator:
    image: "holt-validator-recipe-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: ro

  Formatter:
    image: "holt-formatter-recipe-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: rw

services:
  redis:
    image: redis:7-alpine