version: "1.0"

# M3.8 Terraform Module Generator Demo
# Demonstrates hybrid LLM-and-tool workflow with 6 specialized agents

agents:
  TerraformDrafter:
    image: "holt-terraformdrafter-tf-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: rw  # Needs write access to commit Terraform code
    # M3.9: Realistic health check - verify terraform binary is available
    health_check:
      command: ["terraform", "version"]
      interval: "30s"
      timeout: "5s"

  TerraformFmt:
    image: "holt-terraformfmt-tf-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: ro  # Review agent - read-only access

  TfLint:
    image: "holt-tflint-tf-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: ro  # Review agent - read-only access

  DocGenerator:
    image: "holt-docgenerator-tf-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: rw  # Needs write access to commit documentation

  MarkdownLint:
    image: "holt-markdownlint-tf-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: rw  # Needs write access to commit formatted docs

  ModulePackager:
    image: "holt-modulepackager-tf-demo:latest"
    command: ["/app/run.sh"]
    bid_script: ["/app/bid.sh"]
    workspace:
      mode: ro  # Read-only access to package files

services:
  redis:
    image: redis:7-alpine
