#!/bin/sh
# DocGenerator agent - Generates README.md documentation from Terraform code
# MOCKED VERSION: Uses hardcoded README.md content for deterministic testing

set -e

input=$(cat)
cd /workspace

# Configure git user for commits
git config user.email "docgenerator@holt.demo"
git config user.name "Holt DocGenerator"

# Extract commit hash from target artefact
commit_hash=$(echo "$input" | jq -r '.target_artefact.payload')

echo "DocGenerator: Received TerraformCode commit: $commit_hash" >&2
echo "DocGenerator: Generating module documentation (MOCKED)..." >&2

# Checkout the Terraform code to read it
git checkout "$commit_hash" --quiet

# In production, this would:
# 1. Read main.tf content
# 2. Send to OpenAI API with prompt: "Generate comprehensive README for this Terraform module"
# 3. Parse response and create README.md

# MOCKED LLM RESPONSE: Hardcoded README.md content
cat > README.md <<'EOF'
# S3 Static Website Hosting Module

Terraform module for provisioning an AWS S3 bucket configured for static website hosting with public access.

## Features

- S3 bucket with website hosting configuration
- Public access configuration for static website serving
- Bucket policy for public read access
- Configurable index and error documents
- Outputs for website endpoint and bucket details

## Usage

```hcl
module "static_website" {
  source = "./path/to/module"

  bucket_name = "my-unique-website-bucket"
}
```

### Custom Index and Error Documents

```hcl
module "static_website" {
  source = "./path/to/module"

  bucket_name     = "my-unique-website-bucket"
  index_document  = "home.html"
  error_document  = "404.html"
}
```

## Requirements

| Name | Version |
|------|---------|
| terraform | >= 1.0 |
| aws | ~> 5.0 |

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| bucket_name | Name of the S3 bucket for static website hosting | `string` | n/a | yes |
| index_document | Index document for the website | `string` | `"index.html"` | no |
| error_document | Error document for the website | `string` | `"error.html"` | no |

## Outputs

| Name | Description |
|------|-------------|
| website_endpoint | Website endpoint URL |
| bucket_name | Name of the S3 bucket |
| bucket_arn | ARN of the S3 bucket |

## Important Notes

- This module creates a **publicly accessible** S3 bucket for static website hosting
- Ensure you understand the security implications before deploying
- The bucket policy allows public read access to all objects
- Consider implementing CloudFront for production use cases
- Remember to configure proper DNS records for custom domains

## Example Deployment

After applying this module, upload your website files:

```bash
aws s3 sync ./website-files s3://your-bucket-name
```

Access your website at the endpoint provided in the `website_endpoint` output.

## License

This module is provided as-is for demonstration purposes.

---

*Generated by Holt DocGenerator*
EOF

# Commit the documentation
git add README.md
git commit -m "[holt-agent: DocGenerator] Generated module documentation

Terraform commit: $commit_hash"

new_commit_hash=$(git rev-parse HEAD)

echo "DocGenerator: Committed documentation as $new_commit_hash" >&2

# Output CodeCommit artefact with type "TerraformDocumentation"
cat <<EOF
{
  "artefact_type": "TerraformDocumentation",
  "artefact_payload": "$new_commit_hash",
  "summary": "Generated comprehensive README.md for Terraform module"
}
EOF
