name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.23'

jobs:
  # Unit tests (fast, no Docker required)
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Run unit tests
      run: make test

    - name: Run pup tests
      run: make test-pup

  # Lint checks
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Run linters
      run: make lint

  # Integration and E2E tests (requires Docker)
  integration-tests:
    name: Integration & E2E Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build orchestrator image
      run: make docker-orchestrator

    - name: Build example agent images
      run: |
        docker build -t example-agent:latest -f agents/example-agent/Dockerfile .
        docker build -t example-git-agent:latest -f agents/example-git-agent/Dockerfile .

    - name: Run orchestrator integration tests
      run: make test-integration

    - name: Run E2E tests
      run: make test-e2e
      timeout-minutes: 20

  # Summary job (requires all tests to pass)
  all-tests:
    name: All Tests Passed
    runs-on: ubuntu-latest
    needs: [unit-tests, lint, integration-tests]

    steps:
    - name: Summary
      run: |
        echo "✅ All tests passed successfully!"
        echo ""
        echo "Test Results:"
        echo "  • Unit tests: ✅"
        echo "  • Pup tests: ✅"
        echo "  • Lint: ✅"
        echo "  • Integration tests: ✅"
        echo "  • E2E tests: ✅"
